eks:
    super_secret: ENC[AES256_GCM,data:8HpDxRc=,iv:IGQM3g7jGiNTOACiOA9E1YXHYynzp0NQ+n8gO2Y2o8c=,tag:WIo/Sgop80jUtqMEB5mxww==,type:str]
sops:
    kms:
    -   arn: arn:aws:kms:us-east-1:899755783509:key/6871c190-8634-43ab-af84-3abf9e62dabd
        created_at: '2020-11-09T20:50:54Z'
        enc: AQICAHjN8lZF5/413uequxZUiwKzcPEt4a67I6TLcSGpo29TYQFJNCOAIg6P4MViiT3PPPlDAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMLsCROX/dwPM/VrQfAgEQgDvfaz7Ik85qVeFHS/w3i0/rp1qHGxF6jy18EY6/8Zu3hipOYDKJKx/HyjYfGYFMhtfFq+ztbcLUs9RjLQ==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-11-09T20:51:22Z'
    mac: ENC[AES256_GCM,data:OxySgbWnlQ/TVQGnnTHNIplTmtaemlVLhngIZXPcnyZPEUv2NszZ8ei0FZ6eINzl8/DYzWhG/+KVIx0lbbhMAbNqXEZ8yf7IInz40dCfEy7mZjcWsMFX8b1+s6sxdqsTc5C8Oz9jve7nAIivbq+ODcMCKEau0mqXyqNvIGLfdzc=,iv:oHgT46ECCdNW0H9kJIJqXQ7uMt/Usar8ZYCP690spLw=,tag:7uaYqorikfg+hzSuG8jm2g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.1
